server:
  port: 8800
logging:
  level:
    root: info
  path: E:\logs\
  file: swt-zuul

eureka:
  instance:
    status-page-url: https://localhost:8800/info
spring:
  jpa:
    show-sql: true
    database: MYSQL
  datasource:
    url: jdbc:mysql://192.168.4.216:3306/cloud-recipes?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.4.216
    port: 5672
    username: himasoft
    password: himasoft
  cache:
    type: redis
  redis:
    host: 192.168.4.216
    port: 6379
    password: himasoft
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1000
  sleuth:
    sampler:
      percentage: 1

management:
  security:
    enabled: false
mybatis:
  type-aliases-package: com.himasoft.pojo
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
zuul:
  routes:
    chrs:
      path: /chrs/**
      service-id: chrs

info:
  app:
    name: 网关服务
    description: 网关智能路由中心
    version: v1.0